# Generated by Django 5.2.3 on 2025-06-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spring',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
