# Generated by Django 5.2.3 on 2025-06-25 20:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_spring_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userspring',
            unique_together={('user', 'created_at')},
        ),
    ]
