# Generated by Django 5.2.3 on 2025-06-25 20:28

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_alter_userspring_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userspring',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userspring',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userspring',
            unique_together={('user', 'created_date')},
        ),
    ]
