# Generated by Django 5.2.3 on 2025-06-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_alter_userspring_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspring',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
