# Generated by Django 5.2.3 on 2025-06-25 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_userspring_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userspring',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userspring',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'created_date'), name='unique_active_user_per_day'),
        ),
    ]
