# Generated by Django 5.2.3 on 2025-06-26 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_alter_userspring_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('point', models.PositiveSmallIntegerField()),
                ('step_image', models.ImageField(upload_to='step_images/%Y/%m/%d')),
            ],
            options={
                'db_table': 'step',
            },
        ),
        migrations.CreateModel(
            name='UserStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_step', to='cart_app.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_step', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_step',
            },
        ),
    ]
