# Generated by Django 5.2.3 on 2025-06-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_step_userstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
