# Generated by Django 5.2.3 on 2025-06-25 11:55

import account_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_user_groups_user_is_active_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/%Y/%m/%d', validators=[account_app.validators.max_upload_image_profile]),
        ),
    ]
