# Generated by Django 5.2.3 on 2025-06-26 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_user', models.ForeignKey(help_text='از کاربر', on_delete=django.db.models.deletion.PROTECT, related_name='from_user_invite', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='به کاربر', on_delete=django.db.models.deletion.PROTECT, related_name='to_user_invite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_invite',
            },
        ),
    ]
