# Generated by Django 5.2.3 on 2025-06-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_userinvite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinvite',
            unique_together={('from_user', 'to_user')},
        ),
    ]
